"""about me and last seen

Revision ID: 09babcb7036d
Revises: ed5d18eb185c
Create Date: 2020-11-03 09:56:00.576641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09babcb7036d'
down_revision = 'ed5d18eb185c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=280), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
