"""add display name to user

Revision ID: 27e09510dcd0
Revises: 9cbca4207a93
Create Date: 2020-11-02 10:23:40.778594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27e09510dcd0'
down_revision = '9cbca4207a93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('display_name', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_display_name'), 'user', ['display_name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_display_name'), table_name='user')
    op.drop_column('user', 'display_name')
    # ### end Alembic commands ###
