"""uuid

Revision ID: e20dfe1f8af1
Revises: b6ddf6f07a3b
Create Date: 2020-11-14 14:37:24.992688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e20dfe1f8af1'
down_revision = 'b6ddf6f07a3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('uuid', sa.String(), nullable=True))
    op.create_index(op.f('ix_post_uuid'), 'post', ['uuid'], unique=True)
    op.add_column('user', sa.Column('uuid', sa.String(), nullable=True))
    op.create_index(op.f('ix_user_uuid'), 'user', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_uuid'), table_name='user')
    op.drop_column('user', 'uuid')
    op.drop_index(op.f('ix_post_uuid'), table_name='post')
    op.drop_column('post', 'uuid')
    # ### end Alembic commands ###
