"""timestamp in followers table

Revision ID: ed5d18eb185c
Revises: 544e3ac81e4c
Create Date: 2020-11-02 19:18:41.226696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed5d18eb185c'
down_revision = '544e3ac81e4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('followers', sa.Column('timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('followers', 'timestamp')
    # ### end Alembic commands ###
